import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header/Header";
import Footer from "@/components/shared/Footer";
import Newsletter from "@/components/shared/Newsletter";
import Breadcrumb from "@/components/shared/Breadcrumb";
import Providers from "@/providers/Providers";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Eco Bazar",
  description: "Generated by eco bazar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="flex flex-col min-h-screen">
        <Header />
        <Breadcrumb />
        <section className="flex-1">
          <Providers>{children}</Providers>
        </section>
        <Newsletter />
        <Footer />
      </body>
    </html>
  );
}
